Repository pmachapman/GoTo.Bible, pull requests merged in 2024-10, with the labels that each got.

#433 Update NetBible.cs
  GoToBible.Providers/NetBible.cs
Labels: bug

#439 Fix 3 John 1:15 in the NET
  GoToBible.Providers/NetBible.cs
Labels: bug

#443 Remove the NET Bible from the Web API
  GoToBible.Web/Server/Program.cs
Labels: bug

#444 Minor code clean up
  .editorconfig
  GoToBible.Model/ExtensionMethods.cs
  GoToBible.Model/GoToBible.Model.csproj
  GoToBible.Providers/BundledTranslations.cs
  GoToBible.Web/Client/GoToBible.Web.Client.csproj
  GoToBible.Windows/FormMain.cs
Labels: enhancement

#442 Version bump to 1.5.2
  GoToBible.Model/GoToBible.Model.csproj
  GoToBible.Windows/Properties/AssemblyInfo.cs
Labels: to do

#449 Update Qodana Linter to 2024.2
  GoToBible.Windows/Properties/Resources.resx
  qodana.yaml
Labels: dependencies, github_actions
